### PR TITLE
Add Sindre Sorhus

### PR DESCRIPTION
**Pull request by sindresorhus**
## What type of PR is this? (check all applicable)

- [x] 🚀 Added Name
- [ ] ✨ Feature
- [ ] ✅ Joined Community
- [ ] 🌟 ed the repo
- [ ] 🐛 Grammatical Error
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description

My profile. If it doesn't load, try refreshing some times. It loads eventually.

## Add Link of GitHub Profile

https://github.com/sindresorhus

### CODE REVIEW

**Comment by ABSphreak** [comment]
I see what you did there @sindresorhus 🤣

**Comment by sindresorhus** [comment]
> It Looks Great to me, but could you please resolve conflicts?

What conflicts? If you mean the checks, they were failing for unrelated reasons: https://github.com/abhisheknaiidu/awesome-github-profile-readme/pull/78/checks?check_run_id=883519367 (Cloudflare is down)

> and also could you place https://github.com/sindresorhus/sindresorhus instead of https://github.com/sindresorhus

FYI, there are some other entries that link directly to the profile too.

**Comment by abhisheknaiidu** [comment]
@sindresorhus Okk Fine, I'm merging nw
yea I just saw that there is one, that links to the profile 😅
Thanks for pointing out!

**Comment by ABSphreak** [comment]
Welcome to the repo, @sindresorhus 😍

**Pull request merged**
