### PR TITLE
Add artogahr

### PR DESCRIPTION
**Pull request by artogahr**
## What type of PR is this? (check all applicable)

- [X] 🚀 Added Name
- [ ] ✨ Feature
- [ ] ✅ Joined Community
- [ ] 🌟 ed the repo
- [ ] 🐛 Grammatical Error
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Add Link of GitHub Profile
github.com/artogahr

### CODE REVIEW

**Review by abhisheknaiidu — CHANGES_REQUESTED** [review]
Looks Good, but resolve merge conflicts.

**Comment by artogahr** [comment]
Hi! Sorry but I couldn't find any meaningful conflict that I was able to solve, can you point me to what I'm doing wrong?

**Comment by abhisheknaiidu** [comment]
@artogahr  Just once again, pull the repo and add you're name in the last of `minimalistic` category.

**Comment by artogahr** [comment]
Hi again! Unfortunately since then I deleted the fork, but if you still want to merge, I've created a new PR from a new fork [here.](https://github.com/abhisheknaiidu/awesome-github-profile-readme/pull/310) Since the pull is from the latest version, there should be no conflicts, and if there are, I'm happy to solve.

Thank you again, have a nice day.

**Pull request closed without merging**
