### PR TITLE
Added Pavan Gandhi in the Dynamic Realtime Category

### PR DESCRIPTION
**Pull request by iampavangandhi**
## What type of PR is this? (check all applicable)

- [x] 🚀 Added Name
- [ ] ✨ Feature
- [ ] 🐛 Grammatical Error
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description
Added My Github Profile in the Dynamic Realtime Category.

## Add Link of GitHub Profile
https://github.com/iampavangandhi

### CODE REVIEW

**Comment by iampavangandhi** [comment]
@abhisheknaiidu Please review and merge my PR

**Comment by iampavangandhi** [comment]
@abhisheknaiidu Changed

**Comment by iampavangandhi** [comment]
@abhisheknaiidu Sorry for that. Fixed the README.md Check now.

**Comment by ABSphreak** [comment]
Delete your fork, re-fork, do your changes, then raise a PR, @iampavangandhi

**Pull request closed without merging**
