### PR TITLE
➕Adding new tool : Resolution for #68

### PR DESCRIPTION
**Pull request by ABSphreak**
## What type of PR is this? (check all applicable)

- [ ] 🚀 Added Name
- [ ] ✨ Feature
- [ ] ✅ Joined Community
- [ ] 🌟 ed the repo
- [ ] 🐛 Grammatical Error
- [x] 📝 Documentation Update
- [ ] 🚩 Other

## Description
See #68

### CODE REVIEW

**Comment by ABSphreak** [comment]
Nothing is changes I copied your RAW README file and pasted into mine...
Nothing is changed...
If you feel that this got wrong...you can close this PR.

**Comment by abhisheknaiidu** [comment]
@ABSphreak 

Screenshot 2020-07-17 at 2 25 41 PM

Do one thing do `git pull your-forked-repo-url`
and make those changes, it will be fine :)

**Comment by ABSphreak** [comment]
okay

**Comment by abhisheknaiidu** [comment]
yup, this is because you commited some changes, do 
 - `git log` to see the number of commits, that's causing issue
- then do `git reset --keep HEAD~no-of-commits-you-want-to-go-back`

**Comment by ABSphreak** [comment]
Do I push after that? Push is failing, or I commit?
image

**Comment by abhisheknaiidu** [comment]
> Do I push after that? Push is failing, or I commit?
> image

do `push --force`

**Comment by ABSphreak** [comment]
Did this PR auto-close?
Push has succeeded.

**Comment by abhisheknaiidu** [comment]
> Did this PR auto-close?
> Push has succeeded.

It shows that you've closed it

**Comment by ABSphreak** [comment]
Anyway, I don't know how that happened but we were gonna close it anyway...
Tell me what do I do now to sync my fork to your repo?

**Comment by abhisheknaiidu** [comment]
> Anyway, I don't know how that happened but we were gonna close it anyway...
> Tell me what do I do now to sync my fork to your repo?

git pull "main-repo-url"

**Pull request closed without merging**
