### PR TITLE
Add name to Icons section

### PR DESCRIPTION
**Pull request by peterthehan**
## What type of PR is this? (check all applicable)

- [x] 🚀 Added Name
- [ ] ✨ Feature
- [ ] 🐛 Grammatical Error
- [ ] 📝 Documentation Update
- [x] 🚩 Other

## Description
- Added self
- Ran prettier on the readme for consistent formatting

## Add Link of GitHub Profile
https://github.com/peterthehan

### CODE REVIEW

**Comment by peterthehan** [comment]
@hussainweb I happened to check your readme since I added myself to the same section as yourself and your icons seem to be breaking, just a heads up 😔

**Comment by abhisheknaiidu** [comment]
@peterthehan Nice Catch!, will it be better if we run `prettier` using GitHub Actions?

**Comment by hussainweb** [comment]
Thanks @peterthehan. As far as I can say, it's a bug with GitHub. I can work around that by using absolute URLs in images. Maybe eventually but I'm hoping GitHub fixes the bug before then. :) I have noted this as I created the repo in [my video](https://youtu.be/UqNbBe3lVCI).

The README works properly on the actual [profile page](https://github.com/hussainweb). I am wondering if this README should link to that rather than repositories. 🤔

**Comment by hussainweb** [comment]
> Nice Catch!, will it be better if we run prettier using GitHub Actions?

@abhisheknaiidu I don't think prettier would be able to convert links to absolute URLs, would it?

**Comment by peterthehan** [comment]
> The README works properly on the actual profile page. I am wondering if this README should link to that rather than repositories. 🤔

I don't think I have a strong preference either way, slightly leaning towards the profile page over the repo, but it should be consistent whichever way @abhisheknaiidu calls it.

**Comment by hussainweb** [comment]
@peterthehan, yes. I'm fine either way. I'm just hoping GitHub fixes the issue so that both repo and profile page works properly. I have reported the issue to GitHub. Let's see. If it takes more time, I'll bite the bullet and convert the links to absolute.

**Comment by peterthehan** [comment]
> @abhisheknaiidu I don't think prettier would be able to convert links to absolute URLs, would it?

I think this was in reference to my PR running prettier on the readme. It appears an new issue was opened for this https://github.com/abhisheknaiidu/awesome-github-profile-readme/issues/29

**Comment by abhisheknaiidu** [comment]
> > @abhisheknaiidu I don't think prettier would be able to convert links to absolute URLs, would it?
> 
> I think this was in reference to my PR running prettier on the readme. It appears a new issue was opened for this feature #29

Yup @peterthehan I actually setup'ed GitHub Actions for `Prettier Handling`,but then also it shows the same issue

**Comment by Goldwaage** [comment]
@all-contributors please add peterthehan for doc

**Pull request merged**
