### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Shanu1515**

### CODE REVIEW

**Comment by abhisheknaiidu** [comment]
@Shanu1515 It's not dyanamic bro

**Comment by Shanu1515** [comment]
@abhisheknaiidu okay,so which category will it come under?

**Comment by abhisheknaiidu** [comment]
@Shanu1515 Do one thing, Add it under GIF Category, 
P.S - But I can't guarantee you, whether you will have the place in future or not, because of so much competition :)

**Comment by Shanu1515** [comment]
Added in GIF section

**Comment by abhisheknaiidu** [comment]
@Shanu1515 I have merged it 🎉 
P.S - Don't forget to leave a ⭐ if you found this useful.

**Pull request merged**
