### PR TITLE
Added My Name and Gitwar Profile Score Tool in README.md

### PR DESCRIPTION
**Pull request by iampavangandhi**
## What type of PR is this? (check all applicable)

- [x] 🚀 Added Name
- [ ] ✨ Feature
- [ ] ✅ Joined Community
- [ ] 🌟 ed the repo
- [ ] 🐛 Grammatical Error
- [x] 📝 Documentation Update
- [ ] 🚩 Other

## Description

Added my name in Dynamic Realtime and Gitwar Profile Score in Tools

## Add Link of GitHub Profile

[https://github.com/iampavangandhi](https://github.com/iampavangandhi)

### CODE REVIEW

**Comment by iampavangandhi** [comment]
@abhisheknaiidu Kindly Review my PR

**Comment by iampavangandhi** [comment]
> Looks good to me.

@ABSphreak Then Kindly Merge it

**Comment by ABSphreak** [comment]
> @ABSphreak Then Kindly Merge it

No, merge rights.

**Review by abhisheknaiidu — APPROVED** [review]
Thanks!

**Pull request merged**
