### PR TITLE
Add Tushar Mittal profile and Random Meme tool

### PR DESCRIPTION
**Pull request by techytushar**
## What type of PR is this? (check all applicable)

- [x] 🚀 Added Name
- [x] ✨ Feature
- [ ] ✅ Joined Community
- [ ] 🌟 ed the repo
- [ ] 🐛 Grammatical Error
- [x] 📝 Documentation Update
- [ ] 🚩 Other

## Description

Add **Tushar Mittal profile** in the **Little bit of everything section**, and **random meme generator** in the **Tools** section. 

## Add Link of GitHub Profile

[https://github.com/techytushar/techytushar](https://github.com/techytushar/techytushar)

### CODE REVIEW

**Review by abhisheknaiidu — CHANGES_REQUESTED** [review]
You don't have GIF, GitHub Action. better add it under `badges` category

**Comment by techytushar** [comment]
How about adding it to the `Simple but Innovative Ones` category ?

**Comment by abhisheknaiidu** [comment]
> How about adding it to the `Simple but Innovative Ones` category ? Actually, I don't have any badges on the profile readme, so that might not be the best category.

Fine Add it~

**Comment by techytushar** [comment]
Done! :rocket:

**Review by abhisheknaiidu — APPROVED** [review]
Thanks!

**Pull request merged**
