### PR TITLE
➕ Adding Tool

### PR DESCRIPTION
**Pull request by ABSphreak**
## What type of PR is this? (check all applicable)

- [ ] 🚀 Added Name
- [ ] ✨ Feature
- [ ] ✅ Joined Community
- [ ] 🌟 ed the repo
- [ ] 🐛 Grammatical Error
- [x] 📝 Documentation Update
- [ ] 🚩 Other

## Description
#68 and #70

### CODE REVIEW

**Comment by ABSphreak** [comment]
Is this right now?

**Comment by abhisheknaiidu** [comment]
> Is this right now?
> 
> It still shows so many changes in my committed file.
> 
> I think I might have to delete the fork?
> Why is this happening? 😒

Weird, donno bro, yea delete it and again do fork!

**Comment by ABSphreak** [comment]
Would that delete my contributions?

**Comment by abhisheknaiidu** [comment]
> Would that delete my contributions?

No bro!

**Pull request closed without merging**
