### PR TITLE
Added codeSTACKr profile and video

### PR DESCRIPTION
**Pull request by codeSTACKr**
## What type of PR is this? (check all applicable)

- [x] 🚀 Added Name
- [ ] ✨ Feature
- [ ] ✅ Joined Community
- [ ] 🌟 ed the repo
- [ ] 🐛 Grammatical Error
- [ ] 📝 Documentation Update
- [x] 🚩 Other

## Description
Added my profile under the Actions category and also my video under Tutorials.

## Add Link of GitHub Profile
[codeSTACKr](https://github.com/codestackr)

### CODE REVIEW

**Comment by ABSphreak** [comment]
@codeSTACKr welcome to the repo, love your work on YouTube!

**Comment by codeSTACKr** [comment]
🙏 💜

**Comment by codeSTACKr** [comment]
I'll be featuring this repo in my next video :)

**Comment by ABSphreak** [comment]
Nice! 💕

**Comment by SatyamAaditya** [comment]
Nice 👌

**Comment by JustKwanna** [comment]
Nice :+1:

**Comment by Salah-Zkara** [comment]
Nice <3

**Comment by nhelchitnis** [comment]
Nice

**Pull request merged**
